### ISSUE TITLE
RF code suggestion/question

### ISSUE THREAD

**Issue by ASchneiderBR** [dimagoltsman/Random-Broadlink-RM-Code-Generator#1]
Hello sir! 

If I may, I would like to ask you something, maybe to improve your great project: I have learn a new code with my RM PRO 2 using the learn_command service. Since I've done it twice, I got two different codes, from the same 433 controller.

Here they are:

```
- sgAKAw0MDgwNDA0MDgwNfg0YDhgOGBsLDhgaDA4YDhgNGQ0ZDRkNGQ0ZGgwaDBoLGwwaCw4ZGgsOGA4YDRkaDA4YDRkNGQ0ZGgwNGQ0ZDRkNGRoLGwsOGA4YGgwOGA0ZGgwNGRoMDRkaDA0ZDRkaDA0ZGgsbDBoLGwsaDBoMGgwaDBoMGgwaDBoMDRkaDBoMGgsbAAH5DQwOCw4MDQwNDA4LDgwNDA4MDQsODA1
- sgD6ARoMGgwaDBoMGgwaDBoMGgsaDBoMDhgaDBoMGgwNAAIGDQwODA0MDgsODA0MDQwOCw4MDQwOCw5
```
Why this happens? I've noticed that the light flashes for longer time with the longer code. I am not sure that this is related to repeat or something like that.

Is there a way to do this with your code? To make it longer or shorter, maybe even simplify the code?

I wonder because they both do the same...

Thanks a lot my friend!

**Comment by dimagoltsman** [comment]
sorry for the late response, didnt see it.

thats the same code but you probably held it longer... 
it will be every time different since the rf  reader have some to tolerance. basically  the code is pulses of high and low. for example:

your decoded code(base64 to hex) is:
`b200 fa01 1a0c 1a0c 1a0c 1a0c 1a0c 1a0c 1a0c 1a0b 1a0c 1a0c 0e18 1a0c 1a0c 1a0c 0d00 0206 0d0c 0e0c 0d0c 0e0b 0e0c 0d0c 0d0c 0e0b 0e0c 0d0c 0e0b 0e40`


where `b200` is protocol (RF), `fa` is number of repeats and the rest is pulses.
`1a0c` is "high" and `odoc` is "low"
and `1aob` is almost the same as `1a0c` (1a0c - 1 = 1a0b) but its still ok due to tolerance.
same for `0e0c` and `0e00` or close numbers (hex)

since its rf, an analog data, there are interferences.

**Comment by ASchneiderBR** [comment]
No worries! Thanks for your reply! Let me know if you need anything.

**Comment by ASchneiderBR** [comment]
Hello @dimagoltsman! Just a quick question: did you take a look at the GlobalCache site? I really believe that this could be the final solution to get IR codes and use with your code generator... Thanks a lot my friend! http://www.globalcache.com/files/docs/API-GlobalIRDB_ver1.pdf
